### ISSUE TITLE
longllm position extending

### ISSUE THREAD

**Issue by disperaller** [FlagOpen/FlagEmbedding#849]
Just wanna ask what method are being used when doing position interpolation, is it standard PI? or NTK-aware? in the README file under longllm, most parts focus on implementation of the code, didn't find anything related to the underlying methodology of the position interpolation.
In addition, in the running script provided, the rope theta is set to 200e6, and the target context length is 80k. I couldn't build the connection of where 200e6 comes from. As the original llama3 8b supports 8k context length and the rope theta was set to 0.5e6, if we want to interpolate to 80k, shouldn't the rope theta be set to 5e6 instead of 200e6? Do you have a particular reason or blog explaining why this number is chosen?
Thanks in advance.

**Comment by namespace-Pt** [comment]
Hi, unlike position interpolation that down-scales the position indices, we increase the rope base. This is akin to the ntk interpolation but is easier to implement, see [here](https://github.com/huggingface/transformers/blob/09f9f566de83eef1f13ee83b5a1bbeebde5c80c1/src/transformers/models/llama/modeling_llama.py#L166). The scaling factor, in this case, does not equal to (expected context length)/(original context length). Instead, it is somehow larger. We choose 200e6 because it is large enough for the model to learn the new position embeddings. Some long-context llama3 also use a big rope base, see [here](https://huggingface.co/gradientai/Llama-3-8B-Instruct-262k).

**Comment by disperaller** [comment]
> Collaborator

Got it. Thank you so much for the clarification :)
